### ISSUE TITLE
Stack level too deep on db:schema:dump

### ISSUE THREAD

**Issue by sharq1** [thoughtbot/scenic#140]
That's what I got after migrating first view.
The view is correct as it was working before, I installed gem to have the view dumped in schema.rb

```
$ rake --trace db:migrate
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:migrate
** Invoke db:_dump (first_time)
** Execute db:_dump
** Invoke db:schema:dump (first_time)
** Invoke environment
** Invoke db:load_config
** Execute db:schema:dump
rake aborted!
SystemStackError: stack level too deep
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/foreigner-1.7.2/lib/foreigner/schema_dumper.rb:44:in `tables_with_foreign_keys'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/scenic-1.1.1/lib/scenic/schema_dumper.rb:7:in `tables'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/foreigner-1.7.2/lib/foreigner/schema_dumper.rb:44:in `tables_with_foreign_keys'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/scenic-1.1.1/lib/scenic/schema_dumper.rb:7:in `tables'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/foreigner-1.7.2/lib/foreigner/schema_dumper.rb:44:in `tables_with_foreign_keys'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/scenic-1.1.1/lib/scenic/schema_dumper.rb:7:in `tables'

...

/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.1.12/lib/active_record/schema_dumper.rb:38:in `dump'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.1.12/lib/active_record/schema_dumper.rb:22:in `dump'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.1.12/lib/active_record/railties/databases.rake:231:in `block (4 levels) in <top (required)>'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.1.12/lib/active_record/railties/databases.rake:230:in `open'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.1.12/lib/active_record/railties/databases.rake:230:in `block (3 levels) in <top (required)>'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.1.12/lib/active_record/railties/databases.rake:42:in `block (2 levels) in <top (required)>'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.1.12/lib/active_record/railties/databases.rake:37:in `block (2 levels) in <top (required)>'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/Users/sharq/Projects/rosemary-conley/bin/rake:8:in `<top (required)>'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:241:in `load'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:241:in `block in load'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:232:in `load_dependency'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:241:in `load'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/sharq/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
-e:1:in `<main>'
Tasks: TOP => db:schema:dump
```

here's the view:
```
SELECT
  custom_foods.id AS personalizable_id,
  'CustomFood' AS personalizable_type,
  custom_foods.created_at AS created_at,
  custom_foods.deleted AS deleted,
  custom_foods.user_id AS user_id,
  custom_foods.title AS title
FROM custom_foods

UNION

SELECT
  saved_meals.id AS personalizable_id,
  'SavedMeal' AS personalizable_type,
  saved_meals.created_at AS created_at,
  saved_meals.deleted AS deleted,
  saved_meals.user_id AS user_id,
  saved_meals.title AS title
FROM saved_meals
```

and the migration:
```
class CreatePersonalFoods < ActiveRecord::Migration
  def up
    create_view :personal_foods

    add_index :saved_meals, [:user_id, :title]
    add_index :custom_foods, [:user_id, :title]
  end

  def down
    remove_index :saved_meals, [:user_id, :title]
    remove_index :custom_foods, [:user_id, :title]

    drop_view :personal_foods
  end
end
```

**Comment by derekprior** [comment]
What version of Scenic are you running?

**Comment by sharq1** [comment]
Latest - 1.2.0

**Comment by derekprior** [comment]
It appears there's something about the interplay between scenic and foreigner that isn't going to well. Unfortunately, the only way to extend schema in rails is to monkey patch, and it appears our monkey patches are conflicting with each other. I'll see if there's anything I can do.

**Comment by derekprior** [comment]
@sharq1 I was able to reproduce this issue with the latest foreigner (1.7.4), but can work around it by making sure `foreigner` is required before `scenic`. The easiest way to do this is to put foreigner ahead of scenic in your gemfile.

Does this work around work for you? Have you any interest in helping to pursue a more robust solution?

**Comment by derekprior** [comment]
To be fair, I didn't test that foreigner still functions appropriately (foreign keys are dumped) when required in this manner.

**Comment by derekprior** [comment]
@sharq1 Did the above workaround work for you?
