### ISSUE TITLE
create_view version: X, revert_to_version: y fails on rollback

### ISSUE THREAD

**Issue by mordocai** [thoughtbot/scenic#144]
We have 18 pre-existing views that we are moving to be managed by scenic instead of basically not being managed at all so I'm doing things a bit different than the docs. This may be the source of our issue, but i'll lay out the details.

Here is what i'm getting in the terminal when I run rake db:rollback:

````
== 20160217231514 MigrateAllViewsToScenic: reverting ==========================
-- drop_view(:call_in_history, {:version=>2, :revert_to_version=>1})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

unknown keyword: version
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/scenic-1.2.0/lib/scenic/statements.rb:54:in `drop_view'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:665:in `block in method_missing'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:634:in `block in say_with_time'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:634:in `say_with_time'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:654:in `method_missing'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:499:in `block in revert'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:498:in `each'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:498:in `revert'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:606:in `exec_migration'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:591:in `block in migrate'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:590:in `migrate'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:768:in `migrate'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/transactions.rb:220:in `transaction'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:1044:in `ddl_transaction'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:959:in `block in migrate'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:955:in `each'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:955:in `migrate'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:830:in `down'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:910:in `move'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:812:in `rollback'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/railties/databases.rake:128:in `block (2 levels) in <top (required)>'
ArgumentError: unknown keyword: version
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/scenic-1.2.0/lib/scenic/statements.rb:54:in `drop_view'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:665:in `block in method_missing'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:634:in `block in say_with_time'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:634:in `say_with_time'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:654:in `method_missing'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:499:in `block in revert'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:498:in `each'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:498:in `revert'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:606:in `exec_migration'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:591:in `block in migrate'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:590:in `migrate'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:768:in `migrate'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/transactions.rb:220:in `transaction'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:1044:in `ddl_transaction'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:959:in `block in migrate'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:955:in `each'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:955:in `migrate'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:830:in `down'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:910:in `move'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:812:in `rollback'
RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/railties/databases.rake:128:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:rollback(See full trace by running task with --trace)

````

My migration is pretty simple, has a bunch of views with:

````
drop_view :view_name, revert_to_version: 1
create_view :view_name, version: 2, revert_to_version: 1
````

I'm going to work around this for now by making explicit up/down methods but wanted to report this in case you consider it a bug.

If you wonder why i'm not using update_view (which probably handles this correctly) that is due to the fact that our views depend on each other in a complicated tangle and so the drops/creates have to be in a certain order. Update view won't work for us.

**Comment by calebthompson** [comment]
Thanks. I don't think this is a bug, but we'll keep it in mind in case anyone else has a similar issue come up.

**Comment by pdfrod** [comment]
I'm having exactly the same issue as @Parmandil.
