### ISSUE TITLE
Does not work in engines

### ISSUE THREAD

**Issue by segantii-alex-falkowski** [thoughtbot/scenic#147]
```
bundle exec rails generate scenic:view

/home/alex/.rvm/gems/ruby-2.2.3@sexi/gems/scenic-1.2.0/lib/generators/scenic/view/view_generator.rb:69:in `views_directory_path': undefined method `join' for nil:NilClass (NoMethodError)
	from /home/alex/.rvm/gems/ruby-2.2.3@sexi/gems/scenic-1.2.0/lib/generators/scenic/view/view_generator.rb:14:in `create_views_directory'
	from /home/alex/.rvm/gems/ruby-2.2.3@sexi/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/alex/.rvm/gems/ruby-2.2.3@sexi/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/alex/.rvm/gems/ruby-2.2.3@sexi/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /home/alex/.rvm/gems/ruby-2.2.3@sexi/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /home/alex/.rvm/gems/ruby-2.2.3@sexi/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /home/alex/.rvm/gems/ruby-2.2.3@sexi/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /home/alex/.rvm/gems/ruby-2.2.3@sexi/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /home/alex/.rvm/gems/ruby-2.2.3@sexi/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/alex/.rvm/gems/ruby-2.2.3@sexi/gems/railties-4.2.5.1/lib/rails/generators.rb:157:in `invoke'
	from /home/alex/.rvm/gems/ruby-2.2.3@sexi/gems/railties-4.2.5.1/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from /home/alex/.rvm/gems/ruby-2.2.3@sexi/gems/railties-4.2.5.1/lib/rails/engine/commands.rb:19:in `require'
	from /home/alex/.rvm/gems/ruby-2.2.3@sexi/gems/railties-4.2.5.1/lib/rails/engine/commands.rb:19:in `<top (required)>'
	from bin/rails:12:in `require'
	from bin/rails:12:in `<main>'

```

**Comment by segantii-alex-falkowski** [comment]
Hopefully I'm doing something wrong :)

**Comment by calebthompson** [comment]
No, that makes sense. You'd need to copy the views directory into the host app along with the migrations you copy over.

**Comment by alanq** [comment]
I'm getting the same error running the generator in an engine. I created a db/views directory in the engine.

**Comment by hooopo** [comment]
@calebthompson I can `rails g migration` in engine, but can't `rails generate scenic:view`, because `views_directory_path': undefined`.

**Comment by caherrerapa** [comment]
Any workaround for this? I'm trying to build a solidus extension so I can't copy the views in the main app 👎
