### ISSUE TITLE
Error if db/views does not exist

### ISSUE THREAD

**Issue by calebthompson** [thoughtbot/scenic#52]
```
/Users/caleb/.rvm/gems/ruby-2.1.2@team/gems/scenic-0.2.0/lib/generators/scenic/view/view_generator.rb:35:in `open': No such file or directory @ dir_initialize - /Users/caleb/code/team/db/views (Errno::ENOENT)
        from /Users/caleb/.rvm/gems/ruby-2.1.2@team/gems/scenic-0.2.0/lib/generators/scenic/view/view_generator.rb:35:in `entries'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@team/gems/scenic-0.2.0/lib/generators/scenic/view/view_generator.rb:35:in `previous_version'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@team/gems/scenic-0.2.0/lib/generators/scenic/view/view_generator.rb:41:in `version'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@team/gems/scenic-0.2.0/lib/generators/scenic/view/view_generator.rb:64:in `definition'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@team/gems/scenic-0.2.0/lib/generators/scenic/view/view_generator.rb:11:in `create_view_definition'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@global/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@global/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@global/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@global/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@global/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@global/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@global/gems/thor-0.19.1/lib/thor/group.rb:234:in `dispatch'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@global/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@team/gems/scenic-0.2.0/lib/generators/scenic/model/model_generator.rb:16:in `invoke_view_generator'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@global/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@global/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@global/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@global/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@global/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@global/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@global/gems/thor-0.19.1/lib/thor/group.rb:234:in `dispatch'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@global/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@team/gems/railties-4.1.5/lib/rails/generators.rb:157:in `invoke'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@team/gems/railties-4.1.5/lib/rails/commands/generate.rb:11:in `<top (required)>'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@team/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `require'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@team/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `block in require'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@team/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@team/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `require'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@team/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:135:in `generate_or_destroy'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@team/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:51:in `generate'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@team/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
        from /Users/caleb/.rvm/gems/ruby-2.1.2@team/gems/railties-4.1.5/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by DamirSvrtan** [comment]
As @calebthompson mentioned, this can now be closed since #61 is merged.
