### ISSUE TITLE
rake db:schema:load fails

### ISSUE THREAD

**Issue by geoffharcourt** [thoughtbot/scenic#55]
My test database was out of sync after trying to revise a view migration. I tried to run `rake db:test:load` to fix the issue, and found the same issue happens if I try to run `rake db:schema:load`

```shell

-- add_index("weather_records", ["time"], {:name=>"index_weather_records_on_time", :using=>:btree})
   -> 0.0077s
-- add_index("weather_records", ["weather_location_id"], {:name=>"index_weather_records_on_weather_location_id", :using=>:btree})
   -> 0.0021s
-- create_view(:pg_stat_statements, {:sql_definition=>"       SELECT pg_stat_statements.userid,\n pg_stat_statements.dbid,\n pg_stat_statements.query,\n pg_stat_statements.calls,\n pg_stat_statements.total_time,\n pg_stat_statements.rows,\n pg_stat_statements.shared_blks_hit,\n pg_stat_statements.shared_blks_read,\n pg_stat_statements.shared_blks_dirtied,\n pg_stat_statements.shared_blks_written,\n pg_stat_statements.local_blks_hit,\n pg_stat_statements.local_blks_read,\n pg_stat_statements.local_blks_dirtied,\n pg_stat_statements.local_blks_written,\n pg_stat_statements.temp_blks_read,\n pg_stat_statements.temp_blks_written,\n pg_stat_statements.blk_read_time,\n pg_stat_statements.blk_write_time\nFROM pg_stat_statements() pg_stat_statements(userid, dbid, query, calls, total_time, rows, shared_blks_hit, shared_blks_read, shared_blks_dirtied, shared_blks_written, local_blks_hit, local_blks_read, local_blks_dirtied, local_blks_written, temp_blks_read, temp_blks_written, blk_read_time, blk_write_time);\n"})
rake aborted!
ActiveRecord::StatementInvalid: PG::DuplicateTable: ERROR:  relation "pg_stat_statements" already exists
: CREATE VIEW pg_stat_statements AS        SELECT pg_stat_statements.userid,
 pg_stat_statements.dbid,
 pg_stat_statements.query,
 pg_stat_statements.calls,
 pg_stat_statements.total_time,
 pg_stat_statements.rows,
 pg_stat_statements.shared_blks_hit,
 pg_stat_statements.shared_blks_read,
 pg_stat_statements.shared_blks_dirtied,
 pg_stat_statements.shared_blks_written,
 pg_stat_statements.local_blks_hit,
 pg_stat_statements.local_blks_read,
 pg_stat_statements.local_blks_dirtied,
 pg_stat_statements.local_blks_written,
 pg_stat_statements.temp_blks_read,
 pg_stat_statements.temp_blks_written,
 pg_stat_statements.blk_read_time,
 pg_stat_statements.blk_write_time
FROM pg_stat_statements() pg_stat_statements(userid, dbid, query, calls, total_time, rows, shared_blks_hit, shared_blks_read, shared_blks_dirtied, shared_blks_written, local_blks_hit, local_blks_read, local_blks_dirtied, local_blks_written, temp_blks_read, temp_blks_written, blk_read_time, blk_write_time);
;
/Users/geoff/cortex/db/schema.rb:644:in `block in <top (required)>'
/Users/geoff/cortex/db/schema.rb:14:in `<top (required)>'
PG::DuplicateTable: ERROR:  relation "pg_stat_statements" already exists
/Users/geoff/cortex/db/schema.rb:644:in `block in <top (required)>'
/Users/geoff/cortex/db/schema.rb:14:in `<top (required)>'
Tasks: TOP => db:schema:load
(See full trace by running task with --trace)
```

Due to some migrations in my history that rely on gems no longer in my application and a large number of total migrations, I'd like to avoid having to edit old migrations and/or temporarily patch them any time I rebuild the db from scratch. Due to a Rails 4.1 bug with rolled-back, edited, and re-played migrations, `db:test:load` is still a Rake command I rely on occasionally to reset my test database.

**Comment by halogenandtoast** [comment]
Do the changes in 325988a401296384e816ce3f2d783c360f9ef317 now fix this problem?

**Comment by geoffharcourt** [comment]
@halogenandtoast, I just dumped my schema using master branch as of 325988a, and the schema dump doesn't contain `pg_stat_statements`, so I'm through my obstacle.

**Comment by derekprior** [comment]
This will be in 0.3.0 releasing momentarily.

**Comment by geoffharcourt** [comment]
@derekprior, thanks for turning this around quickly!
